### ISSUE TITLE
Query - Radio GPIO1

### ISSUE THREAD

**Issue by darksidelemm** [bazjo/RS41_Hardware#2]
Hi - this is amazing work you have done - thanks for sharing it!

In your notes you indicate that GPIO1 on the SI4032 "switches a N-channel MOSFET to heat a reference". Which reference are you referring to here?

I've encountered issues in my re-flights of RS41s for amateur radio use where the Si4032 appears to lose PLL lock when it gets too cold, and goes drifting up the 70cm band, only to drift back downwards and 'lock' back into place as it gets warmer again. (The GPS *appears* to continue operating throughout this period, so I'm not sure its the 26 MHz oscillator failing)
I'm wondering if this is related, and I should be switching a GPIO line...

**Comment by bazjo** [comment]
Thx, Mark!
Please refer to the Frontend Section:
"Five heating resistors R201-205 and the MOSFETs Q203-204, required to control these resistors, as well as an unidentified component R209, which could be a thermistor, are placed on an area delimited by milled slots from the rest of the printed circuit board. No heating of the references could be observed in tests at room temperature." The resistors are most likely to keep the reference resisitors heated, so that only the drift in the oscillators themselves is compensated. The reference resistors are probably relatively temperature stable, so that only a course regulation is neccessary here.

According to your issue with the low board temperature: I have already hesrd the same problem somewhere else, but can't find where. However, I think the IC U206, which I was not able to identify, might be your candidate. My first guess was thar this IC switches the heating for the humidity sensor, and also monitord the current throuhg the heating element, as it is connected to the MCU by two lines and has also what first appear to be shunt resisitors.

On closer inspection, there seems to be more to it. there are far more resistors than neccesaary for a shunt, also there are two banks of resistors in series with a middle tab, which I would not expect for a shunt in this case. So these might be the heating resistors for the board, as they are placed quite central. But until the exact IC is found, we will not know for sure.

The quick fix, which you most likely thought of yourself, would be to add an additional resistor between V_Boost and GND, dissipating around 0.5 W.

When I'll come around testing the RS41 in the climate chamber, I'll make sure to through in one with an RTTY firmware as well, even though I think the chamber in my institute only goes down to -50°C

**Comment by darksidelemm** [comment]
Thanks for the info!
I'd rather not dissipate more power than necessary - If I add a custom resistor I'll place it right over the Si4032 I think.

My firmware (which i've been having issues with) is this one: https://github.com/darksidelemm/RS41HUP

**Comment by bazjo** [comment]
The battery capacity is ~6 Wh for NiMHs and ~9 Wh for Lithium Primaries, so the extra load shouldn't really matter. you could also switch the resistor via an additional MOSFET in a control loop with the Si4032 - creativity is the limit.

Further reverse engineering should be the priority though , as the hardware already semms to be aboard.

**Comment by darksidelemm** [comment]
I had a go at launching one of the new foam-case RS41s - same firmware as before, and I ended up with exactly the same result. As the sonde entered the tropopause, the radio transmitter eventually gave up and started drifting up the band. Very annoying.
I suspect the sondes reliable operation does depend on the operation of those 'heater' resistors.

**Comment by darksidelemm** [comment]
OK, I think the issue is relating to locking the radio chip into transmit mode. If i briefly disable and enable TX on the radio chip, it appears to handle the temperature variations much better. Closing this issue :-)
